// This will ignore lex.rs file as it is autogenerated by rflex
#[rustfmt::skip]
#[allow(clippy::all)]
mod lex;

// This will ignore grammar.rs file as it is autogenerated by rustemo
#[rustfmt::skip]
#[allow(clippy::all)]
#[allow(warnings)]
mod grammar;
// This will ignore grammar_actions.rs file as it is autogenerated by rustemo
#[rustfmt::skip]
#[allow(clippy::all)]
#[allow(warnings)]
mod grammar_actions;
mod grammar_lexer;

pub use grammar::GrammarParser;
pub use grammar_lexer::LexerAdapter;
