// This will ignore lex.rs file as it is autogenerated by rflex
#[rustfmt::skip]
#[allow(clippy::all)]
mod lex;

// This will ignore grammar.rs file as it is autogenerated by rustemo
#[rustfmt::skip]
#[allow(clippy::all)]
#[allow(warnings)]
mod grammar;
// This will ignore grammar_actions.rs file as it is autogenerated by rustemo
#[rustfmt::skip]
#[allow(clippy::all)]
#[allow(warnings)]
mod grammar_actions;
mod context;
mod grammar_lexer;

pub use context::{
    CompilerError, open_lexer_file, open_parser_file, open_symbol_table_file,
    read_source_to_string, set_source_file_path,
};
pub use grammar::GrammarParser;
pub use grammar_lexer::LexerAdapter;
