name: lm-compiler release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-*"
  pull_request:
    branches: ["**"]
    paths:
      - ".github/workflows/releases.yaml"

permissions:
  contents: write
  packages: write

jobs:
  build-compiler:
    strategy:
      matrix:
        include:
          - platform: ubuntu-24.04
            os: linux
            arch: x86_64
          - platform: ubuntu-24.04-arm
            os: linux
            arch: aarch64
          - platform: macos-latest
            os: macos
            arch: aarch64
          - platform: windows-latest
            os: windows
            arch: x86_64
          - platform: windows-11-arm
            os: windows
            arch: aarch64
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout sources
        uses: actions/checkout@v5

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: 1.89.0

      - name: Build compiler
        shell: bash
        run: |
          cargo build --release
          exe_ext=""
          if [[ "${{ matrix.os }}" == "windows" ]]; then exe_ext=".exe"; fi
          FILENAME="lm-compiler-${{ matrix.os }}_${{ matrix.arch }}$exe_ext"
          mv target/release/lm-compiler$exe_ext $FILENAME
          echo "ARTIFACT=$FILENAME" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT }}
          path: ${{ env.ARTIFACT }}

  create-release:
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build-compiler
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./bin
          pattern: "lm-compiler*"

      - name: Get previous tag
        run: |
          name=$(git --no-pager tag --sort=creatordate --merged ${{ github.ref_name }} | tail -2 | head -1)
          echo "PREVIOUS_TAG: $name"
          echo "PREVIOUS_TAG=$name" >> $GITHUB_ENV

      - name: Update CHANGELOG
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fromTag: ${{ github.ref_name }}
          toTag: ${{ env.PREVIOUS_TAG }}
          writeToFile: false

      - name: Finalize Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: ./bin/**/*
          draft: false
          prerelease: false
          tag_name: ${{ github.ref_name }}
          name: "lm-compiler: ${{ github.ref_name }}"
          body: >
            Before running read the [docs](https://github.com/LeanSerra/lm-compiler-rust/blob/${{ env.PREVIOUS_TAG}}/README.md)

            ${{ steps.changelog.outputs.changes }}
